### PR TITLE
Merge develop into chpbeta

### PR DESCRIPTION
**Pull request by Bill-Becker**
_**Just trying to merge develop into chpbeta and get help with resolving conflicts**_

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by Bill-Becker** [comment]
@t-kwasnik @NLaws @zolanaj I'm just trying to merge develop into chpbeta. I noticed there's a good chunk of conflicts related to code I didn't change, so I'm reaching out for help. I maybe did not need to create this new branch called chpbeta_MergeDevelop (up to date with chpbeta), but I did anyway.

@t-kwasnik can you help with the load_profile.py conflict?

@zolanaj and @NLaws can you help with the reopt.jl conflicts?

I will work on the known conflicts in data_manager.py related to relocating Fuel Burn, etc parameters from urdb_parse.py.

**Comment by NLaws** [comment]
@Bill-Becker can we re-base the PR to chpbeta? Otherwise I think that we will have to address the conflicts again when you merge the new branch into chpbeta

**Comment by Bill-Becker** [comment]
@NLaws redoing would certainly would not be good! I was trying to allow for chpbeta to be used/built independent of this while we deal with conflicts, but if there's no way around that I'll just change this to chpbeta <- develop.

**Comment by NLaws** [comment]
@Bill-Becker I cherry-picked most of my commits from develop except those that will require accounting for all the CHP techs in the data_manager and urdb_parse. There are many conflicts in the data_manager which I attempted to fix but there were too many questions about what to do for all the CHP accommodations. For the modelinputs.json you should be able to accept the version in chpbeta branch (now that I added the DemandLookbackRange input to it).

**Review by zolanaj — APPROVED** [review]
utils.jl has been resolved, and I cherry-picked the commits from the WindToBatt+curtailment PR into chpbeta.  There are two conflicts remaining in reopt.jl, and the chpbeta branch should be selected for both if you handle conflicts through the webtool (I think conflicts must be resolved for all files at once if you use the web editor, and I didn't want to introduce a breaking change, so I left them in).

**Pull request merged**
