### PR TITLE
200921 master <- develop

### PR DESCRIPTION
**Pull request by NLaws**
## Bug fixes
- scenario.py was checking for wrong message in exception and raising UnexpectedError instead of WindDownloadError
- a fuel cost bug for scenarios with generators (caused by rates with more than one energy tier).

### CODE REVIEW

**Comment by NLaws** [comment]
@t-kwasnik can you please prioritize this review? It will fix many of the `UnexpectedErrors` that we are getting on production.

**Review by t-kwasnik — APPROVED** [review]

**Comment by t-kwasnik** [comment]
@NLaws approved - let me know if you want me to merge/deploy too

**Comment by NLaws** [comment]
@t-kwasnik thanks and yes please merge and deploy!

**Comment by t-kwasnik** [comment]
Bug fixes
scenario.py was checking for wrong message in exception and raising UnexpectedError instead of WindDownloadError
a fuel cost bug for scenarios with generators (caused by rates with more than one energy tier)

**Pull request merged**
