### PR TITLE
Proforma Cashflow Outputs Reporting from API

### PR DESCRIPTION
**Pull request by t-kwasnik**
## New

Adding new Financial outputs per Duke request:
- developer_annual_free_cashflow_series_us_dollars
- offtaker_annual_free_cashflow_series_bau_us_dollars
- offtaker_annual_free_cashflow_series_us_dollars
- offtaker_discounted_annual_free_cashflow_series_bau_us_dollars
- offtaker_discounted_annual_free_cashflow_series_us_dollars

## Bug Fix
Fix messaging when owner tax and discount percents need to be set to that of the offtaker
Developer generator OM costs now based on new capacity in API-side calculations
Note update on negative NPC in third party proforma spreadsheet

### CODE REVIEW

**Comment by t-kwasnik** [comment]
@sakshi-mishra adding some more outputs that are in the proforma to the API response, can you review?

**Review by danolis — APPROVED** [review]
Looks good Ted. Only suggestion is to change text written to cell F7 on 'Inputs and Outputs' tab to "NOTE: A negative Net Present Cost can occur if incentives are greater than costs." for 3rd party financed proforma

**Comment by t-kwasnik** [comment]
thanks @danolis I'll get this merged after the tests pass now that I've updated that note, if that's good with you?

**Comment by danolis** [comment]
That looks good Ted.

**Pull request merged**
