### PR TITLE
Add Cplex option

### PR DESCRIPTION
**Pull request by NLaws**

### CODE REVIEW

**Comment by NLaws** [comment]
@zolanaj I thought maybe you have Cplex such that you can test this new capability?  At the very least I think that you are best positioned to confirm that I got the right Cplex setting for the gap tolerance.

**Comment by zolanaj** [comment]
@NLaws Thanks or putting this together! Your CPLEX parameters are correct.  Should we add a docker file and instructions for CPLEX to the Wiki as well?  

My CPLEX license is for windows, which will make testing this tricky.  I can also work on getting this installed locally on my Windows machine later this week as well if that helps.

**Comment by NLaws** [comment]
@zolanaj Oh yes I can put the Dockerfile for CPLEX together (note that it will require a cplex-linux.bin file that we cannot provide).

**Comment by NLaws** [comment]
@zolanaj I have to put down adding a cplex docker work flow - already spent too much time on it. See the last commit message for a summary of where I left it off.

**Comment by NLaws** [comment]
this is obsolete with new Julia micro service used to address PyJulia threading issues

**Pull request closed without merging**
