### PR TITLE
Chpbeta merge decomp

### PR DESCRIPTION
**Pull request by zolanaj**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This PR merges reopt.jl and reopt_decomposed.jl.  

* **What is the current behavior?** (You can also link to an open issue here)
There was a large amount of duplicated code in both files, and reopt_decomposed.jl was getting out of date with respect to the most recent changes in reopt.jl.

* **What is the new behavior (if this is a feature change)?**
The behavior is the same, i.e., test results are identical; however, with a single file housing model and decomposition code, there is no need to update two model files moving forward. 

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No breaking change.

* **Other information**:
 One note; handling both the monolith and decomposed models in one collection of constraint-generating functions required a large amount of modification to reopt.jl, particularly in the handling of timestep sets throughout the model.  It's possible to keep the decomposition functions in reopt_decomposed.jl, but most of the changes were to existing functions and so I migrated everything to reopt.jl.

### CODE REVIEW

**Comment by Bill-Becker** [comment]
@zolanaj lot's of changes to reopt.jl! Thanks for this effort which was likely larger than you initially thought. I'm adding @NLaws to review because it's a major change. I will try to review ASAP this week, but I have another project I have focus on Monday-Tuesday.  One thing I noticed was the longer test time in GitHub actions. Do you expect slowdowns from this? I will build this branch on a server and benchmark it for non-CHP and CHP scenarios to check the speed comparison in a more controlled environment.

**Comment by zolanaj** [comment]
@Bill-Becker @NLaws 
Thanks Bill.  I don't anticipate that there should be major changes to runtime, unless there is added processing time associated with using model members m[:*] in the place of parameter calls p[*].  I think previously we discussed that this shouldn't be the case,  (reopt.jl is now a larger file, but I don't think it's such a big increase that compile time would increase all that significantly.)  I agree it would be good to check against the benchmarking cases.

**Comment by zolanaj** [comment]
@NLaws @Bill-Becker commit 545f5a941fdf7e496ca571da0588478cded789ea addresses the separation of decomposition-only functions to a separate .jl file to manage the file size of reopt.jl.  Is it potentially worth moving results handling to a separate file as well?  If so I can do that, perhaps in a separate PR if we want to track it separately.

**Comment by Bill-Becker** [comment]
@zolanaj  Thanks Alex! This looks good. Our servers are currently down due to the Rancher/Kubernetes migration, so I'm not able to benchmark this to make sure it's not slowing down the run times. Hopefully in the next few days I'll be able to do that.

**Comment by Bill-Becker** [comment]
@zolanaj I'm getting this error stack trace when trying to run the decomposition model through an API post. The test_chp_sizing_decomposition_7pct test passes, so I assume this is related to the difference in how celery runs the run_jump_model task in parallel with an API call.

reo.exceptions.UnexpectedError: ("<class 'RuntimeError'>", "RuntimeError('Julia exception: could not open file /opt/reopt/reo/src/reopt_decomposed.jl\\nStacktrace:\\n [1] include at ./boot.jl:328 [inlined]\\n [2] include_relative(::Module, ::String) at ./loading.jl:1105\\n [3] include(::Module, ::String) at ./Base.jl:31\\n [4] include(::String) at ./client.jl:424\\n [5] #invokelatest#1 at ./essentials.jl:709 [inlined]\\n [6] invokelatest(::Any, ::Any) at ./essentials.jl:708\\n [7] _pyjlwrap_call(::Function, ::Ptr{PyCall.PyObject_struct}, ::Ptr{PyCall.PyObject_struct}) at /root/.julia/packages/PyCall/ttONZ/src/callback.jl:28\\n [8] pyjlwrap_call(::Ptr{PyCall.PyObject_struct}, ::Ptr{PyCall.PyObject_struct}, ::Ptr{PyCall.PyObject_struct}) at /root/.julia/packages/PyCall/ttONZ/src/callback.jl:49',)", ['  File "/opt/reopt/reo/src/run_jump_model.py", line 188, in run_jump_model\n    results = run_decomposed_model(data, model, reopt_inputs)\n'])
celery.app.builtins ERROR    builtins.py::unlock_chord line 91 Chord '1a6035a2-6fb1-4bd2-bc72-0358d885125b' raised: UnexpectedError("<class 'RuntimeError'>", "RuntimeError('Julia exception: could not open file /opt/reopt/reo/src/reopt_decomposed.jl\\nStacktrace:\\n [1] include at ./boot.jl:328 [inlined]\\n [2] include_relative(::Module, ::String) at ./loading.jl:1105\\n [3] include(::Module, ::String) at ./Base.jl:31\\n [4] include(::String) at ./client.jl:424\\n [5] #invokelatest#1 at ./essentials.jl:709 [inlined]\\n [6] invokelatest(::Any, ::Any) at ./essentials.jl:708\\n [7] _pyjlwrap_call(::Function, ::Ptr{PyCall.PyObject_struct}, ::Ptr{PyCall.PyObject_struct}) at /root/.julia/packages/PyCall/ttONZ/src/callback.jl:28\\n [8] pyjlwrap_call(::Ptr{PyCall.PyObject_struct}, ::Ptr{PyCall.PyObject_struct}, ::Ptr{PyCall.PyObject_struct}) 
at /root/.julia/packages/PyCall/ttONZ/src/callback.jl:49',)", ['  File "/opt/reopt/reo/src/run_jump_model.py", line 188, in run_jump_model\n    results = run_decomposed_model(data, model, reopt_inputs)\n'])
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/builtins.py", line 83, in unlock_chord
    propagate=True,
  File "/usr/local/lib/python3.6/site-packages/celery/result.py", line 781, in join
    disable_sync_subtasks=disable_sync_subtasks,
  File "/usr/local/lib/python3.6/site-packages/celery/result.py", line 226, in get
    self.maybe_throw(callback=callback)
  File "/usr/local/lib/python3.6/site-packages/celery/result.py", line 342, in maybe_throw
    self.throw(value, self._to_remote_traceback(tb))
  File "/usr/local/lib/python3.6/site-packages/celery/result.py", line 335, in throw
    self.on_ready.throw(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/vine/promises.py", line 244, in throw
    reraise(type(exc), exc, tb)
  File "/usr/local/lib/python3.6/site-packages/vine/five.py", line 195, in reraise
    raise value

**Comment by Bill-Becker** [comment]
@zolanaj Disregard the above issue! We reverted an update to Xpress.jl (0.11 to 0.12) that Nick L. made about 10 days ago because the API was getting build-errors on our server, and that revert seemed to have fix this issue. It's also possible that the Julia environment inside my docker container was never properly updated after Nick L. made that update to Xpress.jl and somehow that caused the issue. Either way, this seems to be working now. Also since I now am able to build this branch on our server, I'm in the process of benchmarking it to check for slowdowns. I should have definitive results to compare by Tuesday.

**Comment by Bill-Becker** [comment]
@zolanaj I ran some benchmark runs on chpbeta and this branch to compare, only using the monolith model which does not call decomposed_reopt.jl. There is a major slowdown for some reason. This branch is taking ~3x the time for the non-BAU case, and ~8x the BAU case time. Not sure what's going on. The manage.py test time is no where near that difference in time. Is it possible there is an issue where the julia image is not precompiled for this merged reopt.jl file?

Here is a plot of all the runs (the y-axis label should be "reopt_seconds":

image

**Comment by zolanaj** [comment]
@Bill-Becker I tracked down a couple bugs and differences from chpbeta, and the models appear to be identical for a collection of different cases and technology sets now.  I didn't see any meaningful differences in solve times; can you try this version on your end now?

**Comment by Bill-Becker** [comment]
@zolanaj Thanks Alex! I'll benchmark this update.

**Comment by Bill-Becker** [comment]
@zolanaj those fixes seemed to improve the speed, but it's still significantly slower than chpbeta (the last row is a repeat of the first row, but I ran it again just after the revised merge-decomp to make sure there wasn't much variation from computer resources :

reopt_seconds   (s) | Avg Techs | Avg BAU
-- | -- | --
chpbeta | 87 | 32
merge-decomp | 229 | 236
merge-decomp-R1 | 154 | 90
chpbeta repeat | 87 | 30

**Comment by zolanaj** [comment]
@Bill-Becker   Thanks for running this.  Let me try something different.  We might be able to do this through the parameter object instead since things are running quickly through that data structure.

**Pull request closed without merging**
